name: Build & Push Docker Image
on:
  push:
    branches:
    - main
    tags:
    - "*"
permissions:
  id-token: write
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: "linux/amd64,linux/arm64"
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: "linux/amd64,linux/arm64"
    - name: Set metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value={{sha}}
          type=semver,pattern={{version}}
          type=semver,pattern={{raw}}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        file: "Dockerfile"
        builder: ${{ steps.buildx.outputs.name }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
